version: '3'

vars:
  PRESET: '{{if .PRESET}}{{.PRESET}}{{else if or (eq .OS "windows") (eq .OS "Windows_NT")}}windows-mingw{{else}}default{{end}}'

tasks:
  default:
    desc: Build the project
    cmds:
      - task: build

  build:
    desc: Configure and build the project
    cmds:
      - cmake --preset {{.PRESET}}
      - cmake --build --preset {{.PRESET}}

  test:
    desc: Run tests
    cmds:
      - ctest --preset {{.PRESET}}

  format:
    desc: Format C++ and Go code
    cmds:
      - cmake --build --preset {{.PRESET}} --target format

  generate:
    desc: Regenerate FlatBuffers code
    cmds:
      - cmake --build --preset {{.PRESET}} --target generate

  clean:
    desc: Clean build directory
    cmds:
      - cmake -E remove_directory build
