version: '3'

vars:
  PRESET: '{{.PRESET | default "default"}}'

tasks:
  default:
    desc: Build the project
    cmds:
      - task: build

  build:
    desc: Configure and build the project
    cmds:
      - cmake --preset {{.PRESET}}
      - cmake --build --preset {{.PRESET}}

  test:
    desc: Run tests
    cmds:
      - ctest --preset {{.PRESET}}

  format:
    desc: Format C++ and Go code
    cmds:
      - cmake --build --preset {{.PRESET}} --target format

  generate:
    desc: Regenerate FlatBuffers code
    cmds:
      - cmake --build --preset {{.PRESET}} --target generate

  clean:
    desc: Clean build directory
    cmds:
      - rm -rf build
