version: '3'

vars:
  FLATC:
    sh: 'if [ -f ./flatc ]; then echo "./flatc"; else echo "flatc"; fi'

tasks:
  default:
    desc: "Run configure, build, and test"
    cmds:
      - task: all

  all:
    desc: "Configure, build, and test the project"
    cmds:
      - task: configure
      - task: build
      - task: test

  configure:
    desc: "Configure CMake"
    cmds:
      - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    sources:
      - CMakeLists.txt
      - cmake/**/*.cmake

  build:
    desc: "Build the project"
    deps: [configure]
    cmds:
      - cmake --build build --config Release

  test:
    desc: "Run tests"
    deps: [build]
    cmds:
      - ctest --test-dir build -C Release --output-on-failure

  clean:
    desc: "Clean build directory"
    cmds:
      - rm -rf build

  fmt:
    desc: "Format C++ code"
    cmds:
      - find src include tests -name "*.cpp" -o -name "*.h" | xargs clang-format -i

  generate:
    desc: "Generate code from FlatBuffers schema"
    cmds:
      - '{{.FLATC}} --cpp --scoped-enums -o include/types go/protocol/protocol.fbs'
      - '{{.FLATC}} --go -o go/ go/protocol/protocol.fbs'
