// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CommandInvokeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCommandInvokeRequest(buf []byte, offset flatbuffers.UOffsetT) *CommandInvokeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CommandInvokeRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishCommandInvokeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCommandInvokeRequest(buf []byte, offset flatbuffers.UOffsetT) *CommandInvokeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CommandInvokeRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCommandInvokeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CommandInvokeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CommandInvokeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CommandInvokeRequest) CommandName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CommandInvokeRequest) ControlId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CommandInvokeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CommandInvokeRequestAddCommandName(builder *flatbuffers.Builder, commandName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(commandName), 0)
}
func CommandInvokeRequestAddControlId(builder *flatbuffers.Builder, controlId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(controlId), 0)
}
func CommandInvokeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
