package protocol

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestFlatcVersion_NotEmpty pins the FlatcVersion constant non-empty so
// the doctor-side comparison in xll-gen cannot silently match an unset
// value. The build-time wire is: this constant ↔ xll-gen's
// internal/versions.FlatBuffers.
func TestFlatcVersion_NotEmpty(t *testing.T) {
	if FlatcVersion == "" {
		t.Fatal("FlatcVersion is empty; the doctor cross-check in xll-gen would silently pass against any version")
	}
}

// TestFlatcVersion_GeneratedFilesPresent sanity-checks that every
// `*_generated.go` file under go/protocol/ carries the FlatBuffers
// `Code generated` banner. A missing banner here means the file is not
// actually flatc-generated and the FlatcVersion record doesn't apply
// to it — either the file is hand-rolled (deepcopy.go-like) or
// something has gone wrong with the regeneration step.
//
// This is the closest we can get to a banner check without running
// flatc itself; the upstream tool doesn't embed its own version
// number in the generated output.
func TestFlatcVersion_GeneratedFilesPresent(t *testing.T) {
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("read protocol dir: %v", err)
	}
	const banner = "// Code generated by the FlatBuffers compiler. DO NOT EDIT."
	checked := 0
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		if e.IsDir() || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		// Hand-written companions live alongside generated files.
		// Recognize them by inspecting the first line: only generated
		// files carry the banner. Skip files that don't.
		data, err := os.ReadFile(filepath.Join(".", e.Name()))
		if err != nil {
			t.Errorf("read %s: %v", e.Name(), err)
			continue
		}
		if strings.HasPrefix(string(data), banner) {
			checked++
		}
	}
	if checked == 0 {
		t.Fatal("no flatc-generated files found in go/protocol/ — has regeneration broken?")
	}
	t.Logf("verified banner on %d flatc-generated files (FlatcVersion=%s)", checked, FlatcVersion)
}
