// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RtdOnceGridResult struct {
	_tab flatbuffers.Table
}

func GetRootAsRtdOnceGridResult(buf []byte, offset flatbuffers.UOffsetT) *RtdOnceGridResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RtdOnceGridResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishRtdOnceGridResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRtdOnceGridResult(buf []byte, offset flatbuffers.UOffsetT) *RtdOnceGridResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RtdOnceGridResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRtdOnceGridResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RtdOnceGridResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RtdOnceGridResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RtdOnceGridResult) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RtdOnceGridResult) Value(obj *Any) *Any {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Any)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func RtdOnceGridResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RtdOnceGridResultAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func RtdOnceGridResultAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func RtdOnceGridResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
